const { v4: uuidv4 } = require("uuid");

const accountModel = [
  {
    id: uuidv4(),
    item_name: "Monthly Income",
    amount: 10000,
    date: "2023-06-01",
    from: "Google HQ Manhattan",
    category: "Income",
  },
  {
    id: uuidv4(),
    item_name: "Monthly Savings",
    amount: 3666.67,
    date: "2023-06-01",
    from: "Google HQ Manhattan",
    category: "Savings",
  },
  {
    id: uuidv4(),
    item_name: "Rent",
    amount: -3500,
    date: "2023-06-01",
    from: "JP Rental Property",
    category: "Bills",
  },
  {
    id: uuidv4(),
    item_name: "Car Payment",
    amount: -500,
    date: "2023-06-02",
    from: "Toyota",
    category: "Bills",
  },
  {
    id: uuidv4(),
    item_name: "Car Insurance",
    amount: -247.35,
    date: "2023-06-02",
    from: "Progressive Car Insurance",
    category: "Bills",
  },
  {
    id: uuidv4(),
    item_name: "Weekly Groceries",
    amount: -193.73,
    date: "2023-06-03",
    from: "Trader Joe's",
    category: "Groceries",
  },
  {
    id: uuidv4(),
    item_name: "Gas",
    amount: -76.29,
    date: "2023-06-03",
    from: "Shell Gas Station",
    category: "Travel",
  },
  {
    id: uuidv4(),
    item_name: "Pizza and Lava Cake",
    amount: -33.92,
    date: "2023-06-05",
    from: "Domino's Pizza",
    category: "Casual Dining",
  },
  {
    id: uuidv4(),
    item_name: "Weekly Groceries",
    amount: -187.54,
    date: "2023-06-10",
    from: "Trader Joe's",
    category: "Groceries",
  },
  {
    id: uuidv4(),
    item_name: "Gas",
    amount: -72.41,
    date: "2023-06-10",
    from: "Shell Gas Station",
    category: "Travel",
  },
  {
    id: uuidv4(),
    item_name: "Clothes and Shoes",
    amount: -198.23,
    date: "2023-06-13",
    from: "Mall",
    category: "Casual Shopping",
  },
  {
    id: uuidv4(),
    item_name: "Weekly Groceries",
    amount: -195.29,
    date: "2023-06-17",
    from: "Trader Joe's",
    category: "Groceries",
  },
  {
    id: uuidv4(),
    item_name: "Gas",
    amount: -63.47,
    date: "2023-06-17",
    from: "Shell Gas Station",
    category: "Travel",
  },
];

module.exports = accountModel;
